import {
  UserProfile,
  StudyStats,
  Subject,
  RecentDocument,
  StudyTask,
  WeeklyStudyDay,
  QuickMetric,
} from "@/types";

export const MOCK_USER: UserProfile = {
  name: "Durgesh",
  username: "@durgesh_cs",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  college: "VJTI Mumbai",
  branch: "Computer Engineering",
  year: "2nd Year",
  semester: "Semester 3",
  activeCohort: "VJTI Mumbai • CS 2026",
  streakDays: 7,
  longestStreakDays: 14,
  cloudStorageUsedGB: 4.2,
  cloudStorageTotalGB: 10,
  aiTokensUsed: 78000,
  aiTokensTotal: 100000,
};

export const MOCK_STUDY_STATS: StudyStats = {
  totalStudyHours: 34.5,
  hoursTrendPercent: 12,
  currentStreakDays: 7,
  longestStreakDays: 14,
  topicsMastered: 28,
  totalTopics: 42,
  quizAccuracyPercent: 88.4,
  cohortPercentile: 95,
};

export const MOCK_QUICK_METRICS: QuickMetric[] = [
  {
    id: "study_time",
    label: "Total Study Time",
    value: "34.5 hrs",
    trendText: "+12% this week",
    trendType: "positive",
    accent: "indigo",
  },
  {
    id: "streak",
    label: "Current Streak",
    value: "7 Days",
    trendText: "Personal best: 14",
    trendType: "neutral",
    badgeText: "🔥 Active",
    accent: "amber",
  },
  {
    id: "mastery",
    label: "Topics Mastered",
    value: "28 / 42",
    trendText: "66% completion",
    trendType: "positive",
    accent: "emerald",
  },
  {
    id: "accuracy",
    label: "Quiz Accuracy",
    value: "88.4%",
    trendText: "Top 5% of cohort",
    trendType: "badge",
    badgeText: "🏆 Elite",
    accent: "cyan",
  },
];

export const MOCK_SUBJECTS: Subject[] = [
  {
    id: "dsa",
    name: "Data Structures & Algorithms",
    code: "CS301",
    category: "Core Computing",
    accentColor: "#6366F1", // Indigo
    bgGradient: "from-indigo-500/20 via-indigo-500/5 to-transparent",
    totalUnits: 6,
    completedUnits: 4,
    totalTopics: 14,
    masteredTopics: 10,
    currentUnit: {
      unitNumber: 4,
      title: "Self-Balancing Trees & Graph Traversal",
      progressPercentage: 72,
    },
    lastAccessed: "25 mins ago",
    nextExamDate: "Oct 18, 2026",
  },
  {
    id: "cn",
    name: "Computer Networks",
    code: "CS302",
    category: "Systems & Infrastructure",
    accentColor: "#06B6D4", // Cyan
    bgGradient: "from-cyan-500/20 via-cyan-500/5 to-transparent",
    totalUnits: 5,
    completedUnits: 3,
    totalTopics: 12,
    masteredTopics: 8,
    currentUnit: {
      unitNumber: 3,
      title: "Transport Layer: TCP Congestion & Flow Control",
      progressPercentage: 60,
    },
    lastAccessed: "Yesterday",
    nextExamDate: "Oct 21, 2026",
  },
  {
    id: "dbms",
    name: "Database Management Systems",
    code: "CS303",
    category: "Data Systems",
    accentColor: "#8B5CF6", // Violet
    bgGradient: "from-purple-500/20 via-purple-500/5 to-transparent",
    totalUnits: 5,
    completedUnits: 3,
    totalTopics: 10,
    masteredTopics: 7,
    currentUnit: {
      unitNumber: 4,
      title: "ACID Properties, Transactions & Indexing",
      progressPercentage: 85,
    },
    lastAccessed: "2 days ago",
    nextExamDate: "Oct 24, 2026",
  },
  {
    id: "dm",
    name: "Discrete Mathematics",
    code: "MA301",
    category: "Mathematics & Logic",
    accentColor: "#10B981", // Emerald
    bgGradient: "from-emerald-500/20 via-emerald-500/5 to-transparent",
    totalUnits: 4,
    completedUnits: 2,
    totalTopics: 8,
    masteredTopics: 5,
    currentUnit: {
      unitNumber: 2,
      title: "Combinatorics, Recurrence & Generating Functions",
      progressPercentage: 45,
    },
    lastAccessed: "3 days ago",
    nextExamDate: "Oct 28, 2026",
  },
];

export const MOCK_WEEKLY_STUDY: WeeklyStudyDay[] = [
  { day: "Mon", fullDay: "Monday", minutes: 180, targetMinutes: 150, isToday: false },
  { day: "Tue", fullDay: "Tuesday", minutes: 220, targetMinutes: 150, isToday: false },
  { day: "Wed", fullDay: "Wednesday", minutes: 195, targetMinutes: 150, isToday: false },
  { day: "Thu", fullDay: "Thursday", minutes: 240, targetMinutes: 150, isToday: false },
  { day: "Fri", fullDay: "Friday", minutes: 160, targetMinutes: 150, isToday: false },
  { day: "Sat", fullDay: "Saturday", minutes: 310, targetMinutes: 180, isToday: false },
  { day: "Sun", fullDay: "Sunday (Today)", minutes: 275, targetMinutes: 180, isToday: true },
];

export const MOCK_RECENT_DOCUMENTS: RecentDocument[] = [
  {
    id: "doc-1",
    title: "AVL Trees & Red-Black Rotations Explained.pdf",
    subjectName: "Data Structures & Algorithms",
    subjectCode: "CS301",
    subjectColor: "#6366F1",
    fileType: "pdf",
    fileSize: "3.4 MB",
    uploadDate: "Today, 11:20 AM",
    pages: 24,
    aiSummaryReady: true,
  },
  {
    id: "doc-2",
    title: "TCP-vs-UDP_Protocols_DeepDive.pptx",
    subjectName: "Computer Networks",
    subjectCode: "CS302",
    subjectColor: "#06B6D4",
    fileType: "ppt",
    fileSize: "8.1 MB",
    uploadDate: "Yesterday, 4:15 PM",
    pages: 42,
    aiSummaryReady: true,
  },
  {
    id: "doc-3",
    title: "B-Trees & B+Trees Indexing Mechanism.pdf",
    subjectName: "Database Management Systems",
    subjectCode: "CS303",
    subjectColor: "#8B5CF6",
    fileType: "pdf",
    fileSize: "2.1 MB",
    uploadDate: "Sep 11, 2026",
    pages: 16,
    aiSummaryReady: true,
  },
  {
    id: "doc-4",
    title: "Discrete-Probability-Formulas-CheatSheet.notes",
    subjectName: "Discrete Mathematics",
    subjectCode: "MA301",
    subjectColor: "#10B981",
    fileType: "notes",
    fileSize: "680 KB",
    uploadDate: "Sep 09, 2026",
    pages: 6,
    aiSummaryReady: true,
  },
];

export const MOCK_TODAY_TASKS: StudyTask[] = [
  {
    id: "task-1",
    subjectId: "dsa",
    subjectName: "DSA",
    subjectColor: "#6366F1",
    topicTitle: "Spaced Revision: Red-Black Tree Balancing Cases",
    type: "revision",
    dueText: "Due by 4:00 PM",
    isHighPriority: true,
    completed: false,
  },
  {
    id: "task-2",
    subjectId: "cn",
    subjectName: "Networks",
    subjectColor: "#06B6D4",
    topicTitle: "Speed Quiz: Subnetting & CIDR Notation (15 Qs)",
    type: "quiz",
    dueText: "Due by 7:30 PM",
    isHighPriority: false,
    completed: false,
  },
  {
    id: "task-3",
    subjectId: "dbms",
    subjectName: "DBMS",
    subjectColor: "#8B5CF6",
    topicTitle: "Flashcards: 2PL & Concurrency Conflict Serializability",
    type: "flashcards",
    dueText: "Due by 10:00 PM",
    isHighPriority: true,
    completed: false,
  },
];
