import {
  UserProfile,
  StudyStats,
  Subject,
  RecentDocument,
  StudyTask,
  WeeklyStudyDay,
  QuickMetric,
} from "@/types";

export const MOCK_USER: UserProfile = {
  name: "Durgesh",
  username: "@durgesh_cs",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  college: "VJTI Mumbai",
  branch: "Computer Engineering",
  year: "2nd Year",
  semester: "Semester 3",
  activeCohort: "VJTI Mumbai • CS 2026",
  streakDays: 7,
  longestStreakDays: 14,
  cloudStorageUsedGB: 4.2,
  cloudStorageTotalGB: 10,
  aiTokensUsed: 78000,
  aiTokensTotal: 100000,
};

export const MOCK_STUDY_STATS: StudyStats = {
  totalStudyHours: 34.5,
  hoursTrendPercent: 12,
  currentStreakDays: 7,
  longestStreakDays: 14,
  topicsMastered: 28,
  totalTopics: 42,
  quizAccuracyPercent: 88.4,
  cohortPercentile: 95,
};

export const MOCK_QUICK_METRICS: QuickMetric[] = [
  {
    id: "study_time",
    label: "Total Study Time",
    value: "34.5 hrs",
    trendText: "+12% this week",
    trendType: "positive",
    accent: "indigo",
  },
  {
    id: "streak",
    label: "Current Streak",
    value: "7 Days",
    trendText: "Personal best: 14",
    trendType: "neutral",
    badgeText: "🔥 Active",
    accent: "amber",
  },
  {
    id: "mastery",
    label: "Topics Mastered",
    value: "28 / 42",
    trendText: "66% completion",
    trendType: "positive",
    accent: "emerald",
  },
  {
    id: "accuracy",
    label: "Quiz Accuracy",
    value: "88.4%",
    trendText: "Top 5% of cohort",
    trendType: "badge",
    badgeText: "🏆 Elite",
    accent: "cyan",
  },
];

export const MOCK_SUBJECTS: Subject[] = [
  // 1. Engineering: DSA
  {
    id: "dsa",
    name: "Data Structures & Algorithms",
    title: "Data Structures & Algorithms",
    code: "CS301",
    degree: "Engineering",
    semesterOrYear: "Semester 3",
    category: "Core Computing",
    color: "#6366F1",
    accentColor: "#6366F1",
    bgGradient: "from-indigo-500/20 via-indigo-500/5 to-transparent",
    examDate: "Oct 18, 2026",
    nextExamDate: "Oct 18, 2026",
    totalUnits: 6,
    completedUnits: 4,
    totalTopics: 18,
    masteredTopics: 13,
    lastAccessed: "25 mins ago",
    currentUnit: {
      unitNumber: 4,
      title: "Self-Balancing Trees: AVL & Red-Black Trees",
      progressPercentage: 72,
    },
    units: [
      {
        id: "dsa-u1",
        unitNumber: 1,
        title: "Asymptotic Analysis & Recurrences",
        topics: ["Big-O, Big-Omega, Big-Theta", "Master Theorem", "Substitution Method", "Recursion Trees"],
        status: "mastered",
        progressPercentage: 100,
        notesCount: 4,
        flashcardsCount: 22,
      },
      {
        id: "dsa-u2",
        unitNumber: 2,
        title: "Linear Data Structures: Linked Lists, Stacks & Queues",
        topics: ["Doubly & Circular Lists", "Stack Infix to Postfix", "Circular Queues", "Deque Implementation"],
        status: "mastered",
        progressPercentage: 100,
        notesCount: 6,
        flashcardsCount: 30,
      },
      {
        id: "dsa-u3",
        unitNumber: 3,
        title: "Binary Search Trees, Heaps & Priority Queues",
        topics: ["BST Insert/Delete/Search", "Min/Max Heapify", "HeapSort Algorithm", "Priority Queue Applications"],
        status: "mastered",
        progressPercentage: 90,
        notesCount: 5,
        flashcardsCount: 28,
      },
      {
        id: "dsa-u4",
        unitNumber: 4,
        title: "Self-Balancing Trees: AVL & Red-Black Trees",
        topics: ["LL/RR/LR/RL Rotations", "Red-Black Tree Invariants", "Insertion Balancing Cases", "B-Trees & 2-3 Trees"],
        status: "in_progress",
        progressPercentage: 72,
        notesCount: 7,
        flashcardsCount: 35,
      },
      {
        id: "dsa-u5",
        unitNumber: 5,
        title: "Graph Algorithms: BFS, DFS, Dijkstra & MST",
        topics: ["Adjacency Matrix vs List", "Topological Sort & Kahn's Algorithm", "Dijkstra Shortest Path", "Kruskal & Prim MST"],
        status: "in_progress",
        progressPercentage: 45,
        notesCount: 8,
        flashcardsCount: 40,
      },
      {
        id: "dsa-u6",
        unitNumber: 6,
        title: "Dynamic Programming & Greedy Approaches",
        topics: ["0/1 Knapsack Problem", "Longest Common Subsequence", "Matrix Chain Multiplication", "Huffman Coding"],
        status: "not_started",
        progressPercentage: 0,
        notesCount: 3,
        flashcardsCount: 18,
      },
    ],
  },

  // 2. Engineering: CN
  {
    id: "cn",
    name: "Computer Networks",
    title: "Computer Networks",
    code: "CS302",
    degree: "Engineering",
    semesterOrYear: "Semester 3",
    category: "Systems & Infrastructure",
    color: "#06B6D4",
    accentColor: "#06B6D4",
    bgGradient: "from-cyan-500/20 via-cyan-500/5 to-transparent",
    examDate: "Oct 21, 2026",
    nextExamDate: "Oct 21, 2026",
    totalUnits: 5,
    completedUnits: 3,
    totalTopics: 15,
    masteredTopics: 9,
    lastAccessed: "Yesterday",
    currentUnit: {
      unitNumber: 3,
      title: "Transport Layer: TCP Congestion & Flow Control",
      progressPercentage: 60,
    },
    units: [
      {
        id: "cn-u1",
        unitNumber: 1,
        title: "Physical Layer & Transmission Media",
        topics: ["OSI vs TCP/IP Reference Model", "Guided vs Unguided Media", "Multiplexing (FDM, TDM, WDM)", "Switching Techniques"],
        status: "mastered",
        progressPercentage: 100,
        notesCount: 5,
        flashcardsCount: 20,
      },
      {
        id: "cn-u2",
        unitNumber: 2,
        title: "Data Link Layer & MAC Protocols",
        topics: ["Framing & Error Detection (CRC)", "Sliding Window Protocols", "CSMA/CD & Ethernet", "HDLC & Point-to-Point"],
        status: "mastered",
        progressPercentage: 95,
        notesCount: 6,
        flashcardsCount: 25,
      },
      {
        id: "cn-u3",
        unitNumber: 3,
        title: "Network Layer & IPv4/IPv6 Routing",
        topics: ["Classful vs CIDR Subnetting", "Distance Vector vs Link State", "OSPF & BGP Routing", "NAT & ICMP Protocols"],
        status: "in_progress",
        progressPercentage: 60,
        notesCount: 8,
        flashcardsCount: 32,
      },
      {
        id: "cn-u4",
        unitNumber: 4,
        title: "Transport Layer: TCP Congestion & UDP",
        topics: ["TCP 3-Way Handshake", "TCP Tahoe, Reno & AIMD", "Leaky Bucket & Token Bucket", "UDP Datagram Format"],
        status: "in_progress",
        progressPercentage: 40,
        notesCount: 5,
        flashcardsCount: 24,
      },
      {
        id: "cn-u5",
        unitNumber: 5,
        title: "Application Layer & Network Security",
        topics: ["HTTP/1.1 vs HTTP/2 vs HTTP/3", "DNS Resolution Process", "SSL/TLS Handshake", "RSA & Symmetric Cryptography"],
        status: "not_started",
        progressPercentage: 0,
        notesCount: 4,
        flashcardsCount: 16,
      },
    ],
  },

  // 3. Engineering: DBMS
  {
    id: "dbms",
    name: "Database Management Systems",
    title: "Database Management Systems",
    code: "CS303",
    degree: "Engineering",
    semesterOrYear: "Semester 3",
    category: "Data Systems",
    color: "#8B5CF6",
    accentColor: "#8B5CF6",
    bgGradient: "from-purple-500/20 via-purple-500/5 to-transparent",
    examDate: "Oct 24, 2026",
    nextExamDate: "Oct 24, 2026",
    totalUnits: 5,
    completedUnits: 3,
    totalTopics: 14,
    masteredTopics: 10,
    lastAccessed: "2 days ago",
    currentUnit: {
      unitNumber: 4,
      title: "ACID Properties, Transactions & Indexing",
      progressPercentage: 85,
    },
    units: [
      {
        id: "dbms-u1",
        unitNumber: 1,
        title: "Relational Data Model & ER Diagrams",
        topics: ["Entity-Relationship Modeling", "Relational Algebra Operations", "Tuple Relational Calculus", "Integrity Constraints"],
        status: "mastered",
        progressPercentage: 100,
        notesCount: 5,
        flashcardsCount: 24,
      },
      {
        id: "dbms-u2",
        unitNumber: 2,
        title: "SQL & Normalization (1NF to BCNF)",
        topics: ["Complex SQL Joins & Subqueries", "Functional Dependencies", "1NF, 2NF, 3NF, BCNF", "Lossless Decomposition"],
        status: "mastered",
        progressPercentage: 100,
        notesCount: 7,
        flashcardsCount: 30,
      },
      {
        id: "dbms-u3",
        unitNumber: 3,
        title: "Storage, File Structures & Indexing",
        topics: ["Primary vs Secondary Indexing", "B-Trees vs B+ Trees", "Static & Dynamic Hashing", "Buffer Pool Management"],
        status: "mastered",
        progressPercentage: 90,
        notesCount: 6,
        flashcardsCount: 26,
      },
      {
        id: "dbms-u4",
        unitNumber: 4,
        title: "Transactions, Concurrency & Recovery",
        topics: ["ACID Properties", "Conflict & View Serializability", "Two-Phase Locking (2PL)", "ARIES Recovery & WAL"],
        status: "in_progress",
        progressPercentage: 85,
        notesCount: 8,
        flashcardsCount: 34,
      },
      {
        id: "dbms-u5",
        unitNumber: 5,
        title: "NoSQL Databases & Distributed Systems",
        topics: ["CAP Theorem & BASE", "Key-Value & Document Stores", "Consistent Hashing", "Distributed Two-Phase Commit"],
        status: "not_started",
        progressPercentage: 0,
        notesCount: 3,
        flashcardsCount: 15,
      },
    ],
  },

  // 4. Engineering: Discrete Math
  {
    id: "dm",
    name: "Discrete Mathematics",
    title: "Discrete Mathematics",
    code: "MA301",
    degree: "Engineering",
    semesterOrYear: "Semester 3",
    category: "Mathematics & Logic",
    color: "#10B981",
    accentColor: "#10B981",
    bgGradient: "from-emerald-500/20 via-emerald-500/5 to-transparent",
    examDate: "Oct 28, 2026",
    nextExamDate: "Oct 28, 2026",
    totalUnits: 4,
    completedUnits: 2,
    totalTopics: 12,
    masteredTopics: 7,
    lastAccessed: "3 days ago",
    currentUnit: {
      unitNumber: 2,
      title: "Combinatorics, Recurrence & Generating Functions",
      progressPercentage: 45,
    },
    units: [
      {
        id: "dm-u1",
        unitNumber: 1,
        title: "Propositional & Predicate Logic",
        topics: ["Truth Tables & Tautologies", "Normal Forms (CNF, DNF)", "Rules of Inference", "Quantifiers & Proof Methods"],
        status: "mastered",
        progressPercentage: 100,
        notesCount: 4,
        flashcardsCount: 18,
      },
      {
        id: "dm-u2",
        unitNumber: 2,
        title: "Set Theory, Relations & Functions",
        topics: ["Equivalence Relations", "Partial Order & Hasse Diagrams", "Injective/Surjective Functions", "Lattices & Boolean Algebra"],
        status: "mastered",
        progressPercentage: 90,
        notesCount: 5,
        flashcardsCount: 22,
      },
      {
        id: "dm-u3",
        unitNumber: 3,
        title: "Combinatorics & Generating Functions",
        topics: ["Pigeonhole Principle", "Permutations & Combinations", "Linear Recurrence Relations", "Generating Function Solutions"],
        status: "in_progress",
        progressPercentage: 45,
        notesCount: 6,
        flashcardsCount: 28,
      },
      {
        id: "dm-u4",
        unitNumber: 4,
        title: "Graph Theory & Trees",
        topics: ["Euler & Hamiltonian Paths", "Planar Graphs & Euler's Formula", "Graph Coloring & Chromatic Number", "Spanning Trees"],
        status: "not_started",
        progressPercentage: 0,
        notesCount: 4,
        flashcardsCount: 16,
      },
    ],
  },

  // 5. Medicine: Human Anatomy
  {
    id: "med-anat",
    name: "Human Anatomy & Neuroanatomy",
    title: "Human Anatomy & Neuroanatomy",
    code: "MED201",
    degree: "Medicine",
    semesterOrYear: "Year 2",
    category: "Pre-Clinical Sciences",
    color: "#F43F5E",
    accentColor: "#F43F5E",
    bgGradient: "from-rose-500/20 via-rose-500/5 to-transparent",
    examDate: "Nov 12, 2026",
    nextExamDate: "Nov 12, 2026",
    totalUnits: 4,
    completedUnits: 2,
    totalTopics: 16,
    masteredTopics: 9,
    lastAccessed: "4 days ago",
    currentUnit: {
      unitNumber: 2,
      title: "Cranial Nerves & Central Nervous System",
      progressPercentage: 65,
    },
    units: [
      {
        id: "med-u1",
        unitNumber: 1,
        title: "Cardiovascular & Pulmonary Anatomy",
        topics: ["Coronary Circulation & Heart Chambers", "Bronchopulmonary Segments", "Pleura & Mediastinum", "Fetal Circulation Pathways"],
        status: "mastered",
        progressPercentage: 100,
        notesCount: 8,
        flashcardsCount: 45,
      },
      {
        id: "med-u2",
        unitNumber: 2,
        title: "Cranial Nerves & Central Nervous System",
        topics: ["12 Cranial Nerves Pathways", "Circle of Willis & Brain Blood Supply", "Spinal Cord Tracts", "Ventricular System & CSF"],
        status: "in_progress",
        progressPercentage: 65,
        notesCount: 11,
        flashcardsCount: 52,
      },
      {
        id: "med-u3",
        unitNumber: 3,
        title: "Gastrointestinal & Abdominal Viscera",
        topics: ["Peritoneal Cavity & Omentum", "Hepatic Portal System & Biliary Tree", "Stomach & Intestinal Mesentery", "Retroperitoneal Organs"],
        status: "in_progress",
        progressPercentage: 30,
        notesCount: 6,
        flashcardsCount: 30,
      },
      {
        id: "med-u4",
        unitNumber: 4,
        title: "Musculoskeletal & Joint Mechanics",
        topics: ["Brachial Plexus & Upper Limb", "Sciatic Nerve & Lower Limb", "Knee & Shoulder Joint Ligaments", "Compartment Syndromes"],
        status: "not_started",
        progressPercentage: 0,
        notesCount: 5,
        flashcardsCount: 25,
      },
    ],
  },

  // 6. Law: Constitutional Law
  {
    id: "law-const",
    name: "Constitutional Law & Fundamental Rights",
    title: "Constitutional Law & Fundamental Rights",
    code: "LAW102",
    degree: "Law",
    semesterOrYear: "Semester 2",
    category: "Public Jurisprudence",
    color: "#F59E0B",
    accentColor: "#F59E0B",
    bgGradient: "from-amber-500/20 via-amber-500/5 to-transparent",
    examDate: "Nov 05, 2026",
    nextExamDate: "Nov 05, 2026",
    totalUnits: 4,
    completedUnits: 3,
    totalTopics: 12,
    masteredTopics: 9,
    lastAccessed: "5 days ago",
    currentUnit: {
      unitNumber: 3,
      title: "Directive Principles & Fundamental Duties",
      progressPercentage: 80,
    },
    units: [
      {
        id: "law-u1",
        unitNumber: 1,
        title: "Preamble, Citizenship & Judicial Review",
        topics: ["Basic Structure Doctrine (Kesavananda)", "Separation of Powers", "Citizenship Articles 5-11", "Scope of Article 13 & Judicial Review"],
        status: "mastered",
        progressPercentage: 100,
        notesCount: 6,
        flashcardsCount: 30,
      },
      {
        id: "law-u2",
        unitNumber: 2,
        title: "Fundamental Rights (Articles 14-32)",
        topics: ["Right to Equality (Articles 14-18)", "Right to Freedom & Speech (Article 19)", "Protection of Life (Article 21 & Puttaswamy)", "Constitutional Writs (Article 32 & 226)"],
        status: "mastered",
        progressPercentage: 95,
        notesCount: 9,
        flashcardsCount: 42,
      },
      {
        id: "law-u3",
        unitNumber: 3,
        title: "Directive Principles & Fundamental Duties",
        topics: ["Socialist, Gandhian & Liberal Principles", "Enforceability vs Justiciability", "Harmonious Construction Doctrine", "Article 51A Duties"],
        status: "in_progress",
        progressPercentage: 80,
        notesCount: 5,
        flashcardsCount: 22,
      },
      {
        id: "law-u4",
        unitNumber: 4,
        title: "Emergency Provisions & Amendments",
        topics: ["National Emergency (Article 352)", "President's Rule (Article 356)", "Financial Emergency (Article 360)", "Article 368 Amendment Procedure"],
        status: "not_started",
        progressPercentage: 0,
        notesCount: 4,
        flashcardsCount: 18,
      },
    ],
  },

  // 7. Commerce: Financial Accounting
  {
    id: "com-acc",
    name: "Corporate Financial Accounting",
    title: "Corporate Financial Accounting",
    code: "COM201",
    degree: "Commerce",
    semesterOrYear: "Semester 3",
    category: "Financial Sciences",
    color: "#3B82F6",
    accentColor: "#3B82F6",
    bgGradient: "from-blue-500/20 via-blue-500/5 to-transparent",
    examDate: "Nov 08, 2026",
    nextExamDate: "Nov 08, 2026",
    totalUnits: 4,
    completedUnits: 2,
    totalTopics: 12,
    masteredTopics: 6,
    lastAccessed: "6 days ago",
    currentUnit: {
      unitNumber: 2,
      title: "Cash Flow Statements & Ratio Analysis",
      progressPercentage: 50,
    },
    units: [
      {
        id: "com-u1",
        unitNumber: 1,
        title: "Corporate Balance Sheet & Ind-AS / IFRS",
        topics: ["Schedule III Balance Sheet Format", "Revenue Recognition Standards", "Fair Value Measurement", "Deferred Tax Assets/Liabilities"],
        status: "mastered",
        progressPercentage: 100,
        notesCount: 5,
        flashcardsCount: 25,
      },
      {
        id: "com-u2",
        unitNumber: 2,
        title: "Cash Flow Statements & Financial Ratios",
        topics: ["Operating vs Investing vs Financing", "Indirect Method Calculation", "DuPont Analysis", "Liquidity & Solvency Ratios"],
        status: "in_progress",
        progressPercentage: 50,
        notesCount: 6,
        flashcardsCount: 28,
      },
      {
        id: "com-u3",
        unitNumber: 3,
        title: "Valuation of Shares, Debentures & Goodwill",
        topics: ["Net Asset Method", "Yield & PE Multiple Method", "Super Profit Method for Goodwill", "Impairment of Assets"],
        status: "not_started",
        progressPercentage: 0,
        notesCount: 4,
        flashcardsCount: 16,
      },
      {
        id: "com-u4",
        unitNumber: 4,
        title: "Amalgamation, Absorption & Reconstruction",
        topics: ["Purchase Consideration Calculation", "Pooling of Interests Method", "Internal Capital Reduction Scheme", "Accounting for Mergers"],
        status: "not_started",
        progressPercentage: 0,
        notesCount: 5,
        flashcardsCount: 20,
      },
    ],
  },

  // 8. Management: Strategic Operations
  {
    id: "mgt-ops",
    name: "Strategic Operations & Supply Chain",
    title: "Strategic Operations & Supply Chain",
    code: "MGT301",
    degree: "Management",
    semesterOrYear: "Semester 4",
    category: "Executive Management",
    color: "#14B8A6",
    accentColor: "#14B8A6",
    bgGradient: "from-teal-500/20 via-teal-500/5 to-transparent",
    examDate: "Nov 22, 2026",
    nextExamDate: "Nov 22, 2026",
    totalUnits: 4,
    completedUnits: 1,
    totalTopics: 10,
    masteredTopics: 4,
    lastAccessed: "1 week ago",
    currentUnit: {
      unitNumber: 2,
      title: "Supply Chain Network Design & Inventory Control",
      progressPercentage: 35,
    },
    units: [
      {
        id: "mgt-u1",
        unitNumber: 1,
        title: "Operations Strategy & Process Analysis",
        topics: ["Competitive Priorities & Capabilities", "Little's Law & Bottleneck Analysis", "Process Flow Diagramming", "Capacity Utilization"],
        status: "mastered",
        progressPercentage: 100,
        notesCount: 4,
        flashcardsCount: 20,
      },
      {
        id: "mgt-u2",
        unitNumber: 2,
        title: "Supply Chain Design & Inventory Control",
        topics: ["EOQ & Safety Stock Models", "Bullwhip Effect Mitigation", "Vendor Managed Inventory (VMI)", "Facility Location Models"],
        status: "in_progress",
        progressPercentage: 35,
        notesCount: 6,
        flashcardsCount: 26,
      },
      {
        id: "mgt-u3",
        unitNumber: 3,
        title: "Lean Systems, Six Sigma & Quality Control",
        topics: ["Toyota Production System (TPS)", "DMAIC Methodology & Process Capability (Cpk)", "Statistical Process Control (SPC)", "Kaizen & Value Stream Mapping"],
        status: "not_started",
        progressPercentage: 0,
        notesCount: 4,
        flashcardsCount: 18,
      },
      {
        id: "mgt-u4",
        unitNumber: 4,
        title: "Global Logistics & Sustainable Supply Chains",
        topics: ["Incoterms & Freight Management", "Reverse Logistics & Circular Economy", "Risk Hedging in Supply Networks", "Blockchain in Provenance"],
        status: "not_started",
        progressPercentage: 0,
        notesCount: 3,
        flashcardsCount: 15,
      },
    ],
  },
];

export const MOCK_WEEKLY_STUDY: WeeklyStudyDay[] = [
  { day: "Mon", fullDay: "Monday", minutes: 180, targetMinutes: 150, isToday: false },
  { day: "Tue", fullDay: "Tuesday", minutes: 220, targetMinutes: 150, isToday: false },
  { day: "Wed", fullDay: "Wednesday", minutes: 195, targetMinutes: 150, isToday: false },
  { day: "Thu", fullDay: "Thursday", minutes: 240, targetMinutes: 150, isToday: false },
  { day: "Fri", fullDay: "Friday", minutes: 160, targetMinutes: 150, isToday: false },
  { day: "Sat", fullDay: "Saturday", minutes: 310, targetMinutes: 180, isToday: false },
  { day: "Sun", fullDay: "Sunday (Today)", minutes: 275, targetMinutes: 180, isToday: true },
];

export const MOCK_RECENT_DOCUMENTS: RecentDocument[] = [
  {
    id: "doc-1",
    title: "AVL Trees & Red-Black Rotations Explained.pdf",
    subjectName: "Data Structures & Algorithms",
    subjectCode: "CS301",
    subjectColor: "#6366F1",
    fileType: "pdf",
    fileSize: "3.4 MB",
    uploadDate: "Today, 11:20 AM",
    pages: 24,
    aiSummaryReady: true,
  },
  {
    id: "doc-2",
    title: "TCP-vs-UDP_Protocols_DeepDive.pptx",
    subjectName: "Computer Networks",
    subjectCode: "CS302",
    subjectColor: "#06B6D4",
    fileType: "ppt",
    fileSize: "8.1 MB",
    uploadDate: "Yesterday, 4:15 PM",
    pages: 42,
    aiSummaryReady: true,
  },
  {
    id: "doc-3",
    title: "B-Trees & B+Trees Indexing Mechanism.pdf",
    subjectName: "Database Management Systems",
    subjectCode: "CS303",
    subjectColor: "#8B5CF6",
    fileType: "pdf",
    fileSize: "2.1 MB",
    uploadDate: "Sep 11, 2026",
    pages: 16,
    aiSummaryReady: true,
  },
  {
    id: "doc-4",
    title: "Discrete-Probability-Formulas-CheatSheet.notes",
    subjectName: "Discrete Mathematics",
    subjectCode: "MA301",
    subjectColor: "#10B981",
    fileType: "notes",
    fileSize: "680 KB",
    uploadDate: "Sep 09, 2026",
    pages: 6,
    aiSummaryReady: true,
  },
];

export const MOCK_TODAY_TASKS: StudyTask[] = [
  {
    id: "task-1",
    subjectId: "dsa",
    subjectName: "DSA",
    subjectColor: "#6366F1",
    topicTitle: "Spaced Revision: Red-Black Tree Balancing Cases",
    type: "revision",
    dueText: "Due by 4:00 PM",
    isHighPriority: true,
    completed: false,
  },
  {
    id: "task-2",
    subjectId: "cn",
    subjectName: "Networks",
    subjectColor: "#06B6D4",
    topicTitle: "Speed Quiz: Subnetting & CIDR Notation (15 Qs)",
    type: "quiz",
    dueText: "Due by 7:30 PM",
    isHighPriority: false,
    completed: false,
  },
  {
    id: "task-3",
    subjectId: "dbms",
    subjectName: "DBMS",
    subjectColor: "#8B5CF6",
    topicTitle: "Flashcards: 2PL & Concurrency Conflict Serializability",
    type: "flashcards",
    dueText: "Due by 10:00 PM",
    isHighPriority: true,
    completed: false,
  },
];
